"""tag_name

Revision ID: 15a7e4ada98c
Revises: 7e69469f0fa8
Create Date: 2021-02-02 15:45:27.110729

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "15a7e4ada98c"
down_revision = "7e69469f0fa8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tag", sa.Column("name", sa.String(length=127), nullable=True))
    # op.drop_index('text', table_name='tag')
    op.create_unique_constraint(None, "tag", ["name"])
    op.drop_column("tag", "text")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tag", sa.Column("text", mysql.VARCHAR(length=127), nullable=True))
    op.drop_constraint(None, "tag", type_="unique")
    op.create_index("text", "tag", ["text"], unique=True)
    op.drop_column("tag", "name")
    # ### end Alembic commands ###
