"""default priority

Revision ID: 41fad22aac92
Revises: fd5facbc8c77
Create Date: 2021-02-15 16:16:18.117804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "41fad22aac92"
down_revision = "fd5facbc8c77"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("priority", sa.Column("is_default", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("priority", "is_default")
    # ### end Alembic commands ###
