"""todo_tags

Revision ID: 53012f51cfea
Revises: 578c404af351
Create Date: 2021-02-02 15:31:51.298652

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "53012f51cfea"
down_revision = "578c404af351"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tag",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("text", sa.String(length=127), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.alter_column(
        "alarm",
        "retry_delay",
        existing_type=mysql.INTEGER(),
        nullable=True,
        existing_server_default=sa.text("'60'"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "alarm",
        "retry_delay",
        existing_type=mysql.INTEGER(),
        nullable=False,
        existing_server_default=sa.text("'60'"),
    )
    op.drop_table("tag")
    # ### end Alembic commands ###
