"""initial

Revision ID: 578c404af351
Revises:
Create Date: 2021-02-02 15:29:23.738231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "578c404af351"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "alarm",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("text", sa.String(), nullable=True),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("end_at", sa.DateTime(), nullable=True),
        sa.Column("requires_acknowledgment", sa.Boolean(), nullable=True),
        sa.Column("retry_delay", sa.Integer(), nullable=True),
        sa.Column("send_email", sa.Boolean(), nullable=True),
        sa.Column("silent", sa.Boolean(), nullable=True),
        sa.Column(
            "level",
            sa.Enum("NORMAL", "IMPORTANT", name="importancelevel"),
            nullable=True,
        ),
        sa.Column("times_notified", sa.Integer(), nullable=True),
        sa.Column("next_reminder_time_target", sa.DateTime(), nullable=True),
        sa.Column("acknowledged", sa.Boolean(), nullable=True),
        sa.Column("canceled", sa.Boolean(), nullable=True),
        sa.Column("success", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "todo",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("text", sa.String(length=127), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.Column("canceled", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("todo")
    op.drop_table("alarm")
    # ### end Alembic commands ###
