"""projects_relationship

Revision ID: 61025b2d2ab8
Revises: eeed44e449dc
Create Date: 2021-02-03 14:33:29.972929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "61025b2d2ab8"
down_revision = "eeed44e449dc"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("todo", sa.Column("project_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        None, "todo", "project", ["project_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "todo", type_="foreignkey")
    op.drop_column("todo", "project_id")
    # ### end Alembic commands ###
