"""projects_relationship_not_null

Revision ID: 6b47c5bd9dd7
Revises: 61025b2d2ab8
Create Date: 2021-02-03 14:34:45.243463

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6b47c5bd9dd7'
down_revision = '61025b2d2ab8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todo', 'project_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todo', 'project_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
