"""add_priorities

Revision ID: 6ddd90ce82a0
Revises: ea5a53104953
Create Date: 2021-02-09 16:02:26.547651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "6ddd90ce82a0"
down_revision = "ea5a53104953"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "priority",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=127), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["project.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("todo", sa.Column("priority_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        None, "todo", "priority", ["priority_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "todo", type_="foreignkey")
    op.drop_column("todo", "priority_id")
    op.drop_table("priority")
    # ### end Alembic commands ###
