"""tag_relationship_unique

Revision ID: b047b954e461
Revises: b561eecc5b5e
Create Date: 2021-02-02 16:15:03.382675

"""
from alembic import op


# revision identifiers, used by Alembic.
revision = "b047b954e461"
down_revision = "b561eecc5b5e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "tagged", ["tag_id", "todo_id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "tagged", type_="unique")
    # ### end Alembic commands ###
