"""tag_relationship

Revision ID: b561eecc5b5e
Revises: 15a7e4ada98c
Create Date: 2021-02-02 15:55:16.255799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b561eecc5b5e"
down_revision = "15a7e4ada98c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tagged",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tag_id", sa.Integer(), nullable=False),
        sa.Column("todo_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["tag_id"], ["tag.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["todo_id"], ["todo.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tagged")
    # ### end Alembic commands ###
