"""add_level

Revision ID: d53c1e8ae002
Revises: 6ddd90ce82a0
Create Date: 2021-02-09 16:04:47.715587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d53c1e8ae002"
down_revision = "6ddd90ce82a0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("priority", sa.Column("level", sa.Integer(), nullable=True))
    op.create_unique_constraint(None, "priority", ["project_id", "level"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "priority", type_="unique")
    op.drop_column("priority", "level")
    # ### end Alembic commands ###
