"""todo_dag

Revision ID: ea5a53104953
Revises: 6b47c5bd9dd7
Create Date: 2021-02-05 14:26:13.116254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea5a53104953'
down_revision = '6b47c5bd9dd7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dependency',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('child_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['todo.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['todo.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parent_id', 'child_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dependency')
    # ### end Alembic commands ###
