"""comment_text_field

Revision ID: f6ddfdd212f7
Revises: 78bc7345edfb
Create Date: 2021-06-20 11:29:16.827819

"""
from alembic import op


# revision identifiers, used by Alembic.
revision = "f6ddfdd212f7"
down_revision = "78bc7345edfb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE comment ALTER text TYPE TEXT;")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
