"""priority_unique

Revision ID: fd5facbc8c77
Revises: d53c1e8ae002
Create Date: 2021-02-09 17:03:17.511586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd5facbc8c77'
down_revision = 'd53c1e8ae002'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index('name', table_name='priority')
    op.create_unique_constraint(None, 'priority', ['project_id', 'name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'priority', type_='unique')
    op.create_index('name', 'priority', ['name'], unique=True)
    # ### end Alembic commands ###
